name: "🚀 GitOps Continuous Deployment (CD) - Enterprise Edition"

on:
  push:
    branches:
      - main
    paths:
      - "fase-3-api-serverless/**"

jobs:
  terraform-deploy:
    name: "Deploy Infra & Lambda API"
    runs-on: ubuntu-latest

    # 🛠️ MELHORIA 1: Credenciais injetadas globalmente a nível de JOB. 
    # Remove a poluição visual de repetir as chaves em cada step da esteira.
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: ./fase-3-api-serverless

    steps:
      - name: "Checkout do Código"
        uses: actions/checkout@v4

      # Adiciona permissões necessárias para o padrão OIDC no futuro
      permissions:
        id-token: write
        contents: read

      - name: "Configurar o Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Instalar o Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: "Terraform Init"
        run: terraform init -reconfigure

      # 🛠️ MELHORIA 2 (Parte A): Gera o plano de mudanças e salva em um arquivo binário imutável (tfplan).
      # Garante que o que foi revisado aqui será exatamente o que será aplicado no passo seguinte.
      - name: "Terraform Plan"
        run: terraform plan -out=tfplan

      # 🛠️ MELHORIA 2 (Parte B): Executa o apply referenciando o arquivo binário gerado no step anterior.
      # Elimina o uso de "-auto-approve" solto, seguindo a boa prática rígida de segurança corporativa.
      - name: "Terraform Apply (Deploy Seguro)"
        run: terraform apply tfplan
