name: "🚀 GitOps Continuous Deployment (CD) - Enterprise Edition"

on:
  push:
    branches:
      - main
    paths:
      - "fase-3-api-serverless/**"

jobs:
  terraform-deploy:
    name: "Deploy Infra & Lambda API"
    runs-on: ubuntu-latest

    # Permissões declaradas no nível correto do JOB
    permissions:
      id-token: write
      contents: read

    # Credenciais e região injetadas para todo o job
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-2"

    defaults:
      run:
        working-directory: ./fase-3-api-serverless

    steps:
      - name: "Checkout do Código"
        uses: actions/checkout@v4

      - name: "Configurar o Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Instalar o Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: "Terraform Init"
        run: terraform init -reconfigure

      - name: "Terraform Plan"
        run: terraform plan -out=tfplan

      - name: "Terraform Apply (Deploy Seguro)"
        run: terraform apply tfplan
